#!/bin/bash

. "${MPIS_UI}"


REQUIRED=( MPIS_OUTPUT_ROOT MPIS_STDOUT_EXTENSION MPIS_STDERR_EXTENSION MPIS_USER_ID MPIS_COMPILER MPIS_SCHEDULER MACRO VALUES TIME_PATTERN )

RESULTS="results.csv"

function max
{
    list=""

    for value in $*
    do
        list="$value, $list"
    done

    python -c "print(max([${list}]))"
}

if [ "$#" -lt 2 ]
then
    log "ERROR" "usage: $( basename "$0" ) [SOURCE] [DESCRIPTION]"; exit 1
fi

if [ ! -r "$1" ]
then
    log "ERROR" "'$1' is not readable"; exit 1
fi

if [ ! -r "$2" ]
then
    log "ERROR" "'$2' is not readable"; exit 1
fi

. "$2"

for value in "${REQUIRED[@]}"
do
    if [[ -z "${!value// }" ]]
    then
        log "ERROR" "'$value' has not been specified"; exit 1
    fi
done

exe="$( basename "$1" )"
exe="${exe%.*}.x"

DIR="$( date +"%d_%m_%Y" )/$( date +"%H_%M_%S" )"

for value in "${VALUES[@]}"
do
    if ! "$MPIS_COMPILER" "$1" "$MACRO" "$value"
    then
        exit 1
    fi

    for ((processes = 1; processes <= 64; processes *= 2))
    do
        export SCHEDULE_DIRECTORY="${DIR}/${value}/${processes}"

        if ! "$MPIS_SCHEDULER" "$exe" "$processes"
        then
            exit 1
        fi
    done

    while true
    do
        running="$( qstat | grep "$MPIS_USER_ID" )"

        if [ -z "$running" ]
        then
            break
        fi
    done
done

find . -maxdepth 1 -name "*job.sh" -delete
find . -maxdepth 1 -name "*.x"     -delete

for file in $(find "${MPIS_OUTPUT_ROOT}" -name "*.mpiP")
do
    mv "$file" "$(dirname "$file")/mpiP.log"
done

declare -A measurements

for value in "${VALUES[@]}"
do
    for ((processes = 1; processes <= 64; processes *= 2))
    do
        for file in $( find "${MPIS_OUTPUT_ROOT}/${DIR}/${value}/${processes}" -name "*.${MPIS_STDOUT_EXTENSION}" | tr '\n' ' ' )
        do
            values="$( cat "$file" | grep -Po "$TIME_PATTERN" | tr '\n' ' ' )"

            if [[ -z "${values// }" ]]
            then
                log "WARNING" "No matches for '${TIME_PATTERN}' in '$file'"

                if [[ ! -z "${MPIS_EDITOR// }" ]] && [[ "$( command -v "$MPIS_EDITOR" )" ]]
                then
                    "$MPIS_EDITOR" "$MPIS_EDITOR_ARGS" "$file" "${file%%.*}.${MPIS_STDERR_EXTENSION}"
                fi

                measurements["$value, $processes"]="-1"
            else
                measurements["$value, $processes"]="$( max "$values" )"
            fi
        done
    done
done

log "MESSAGE" "Saving measurements to '${MPIS_OUTPUT_ROOT}/${DIR}/${RESULTS}'"

echo "${MACRO}, Processes, Time, Speed Up, Efficiency" > "${MPIS_OUTPUT_ROOT}/${DIR}/${RESULTS}"

for value in "${VALUES[@]}"
do
    for ((processes = 1; processes <= 64; processes *= 2))
    do
        speedup="$( python -c "print(${measurements[$value, 1]} / ${measurements[$value, $processes]})" )"

        efficiency="$( python -c "print(${speedup} / ${processes})" )"

        echo "${value}, ${processes}, ${measurements[$value, $processes]}, ${speedup}, ${efficiency}"
    done
done >> "${MPIS_OUTPUT_ROOT}/${DIR}/${RESULTS}"

if [[ ! -z "${MPIS_EDITOR// }" ]] && [[ "$( command -v "$MPIS_EDITOR" )" ]]
then
    "$MPIS_EDITOR" "$MPIS_EDITOR_ARGS" "${MPIS_OUTPUT_ROOT}/${DIR}/${RESULTS}"
fi
