#!/bin/bash

. "${MPIS_UI}"


if [[ "$*" == *--clean* ]]
then
    find . -name "*.x" -delete; exit 0
fi

if [ "$#" -lt 1 ]
then
    log "ERROR" "usage: $( basename "$0" ) [SOURCE] [MACROS]..."; exit 1
fi

if [ ! -r "$1" ]
then
    log "ERROR" "'$1' is not readable"; exit 1
fi

exe="$( basename "$1" )"
exe="${exe%.*}.x"

args="-O3 -Wall -Wextra"

for ((key = 2; key <= $#; key += 2))
do
    value="$(( $key + 1))"

    if [ "$value" -gt "$#" ]
    then
        log "WARNING" "No value associated with key '${!key}'"
    else
        args="$args -D${!key}=${!value}"
    fi
done

if [[ "$MPIS_ENABLE_PROFILING" == true ]] || ([[ -z "${MPIS_ENABLE_PROFILING+is_set}" ]] && confirm "MESSAGE" "enable profiling")
then
    args="$args -g -L$MPIP_DIR/lib -lmpiP -lbfd -lunwind"
fi

if [[ "$MPIS_LINK_OPENMP" == true ]] || ([[ -z "${MPIS_LINK_OPENMP+is_set}" ]] && confirm "MESSAGE" "link OpenMP")
then
    args="$args -fopenmp"
fi

if ! mpicc $args "$1" -o "$exe"
then
    log "ERROR" "'$1' failed to compile"; exit 1
fi
